[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "triton"
platforms = ["linux-aarch64", "linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.13.*"
uv = ">=0.8.13,<0.9"
ruff = ">=0.14.13,<0.15"
ty = ">=0.0.13,<0.0.14"
debugpy = ">=1.8.20,<2"

pre-commit = ">=4.5.1,<5"
pytest = ">=9.0.2,<10"
lit = ">=21.1.8,<22"
ripgrep = ">=15.1.0,<16"
fd-find = ">=10.3.0,<11"

pybind11 = ">=3.0.1,<4"
pybind11-global = ">=3.0.1,<4"

scipy = ">=1.17.1,<2"
nlohmann_json = ">=3.12.0,<4"

[target.osx-arm64.dependencies]
pytorch = ">=2.10.0,<3"

[pypi-dependencies]
llnl-hatchet = ">=2026.1.0, <2027"

[feature.cu129.system-requirements]
cuda = "12.9"

[feature.cu129.dependencies]
python = "3.13.*"
uv = ">=0.8.13,<0.9"

[feature.cu129.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=12.9 pixi i -e cu129
# CONDA_OVERRIDE_CUDA=12.9 pixi add cuda-version=12.9 cuda-toolkit=12.9.1 -p linux-64 -f cu129
cuda-version = "12.9.*"
cuda-toolkit = "12.9.1.*"
# CONDA_OVERRIDE_CUDA=12.9 pixi add pytorch=2.10.0 torchvision -p linux-64 -f cu129
# works with nightly vllm fo now
pytorch = "2.10.0.*"
torchvision = ">=0.25.0,<0.26"

# cu130
[feature.cu130.system-requirements]
cuda = "13.0"

[feature.cu130.dependencies]
python = "3.13.*"
uv = ">=0.8.13,<0.9"

[feature.cu130.target.linux-64.dependencies]
# CONDA_OVERRIDE_CUDA=13.0 pixi i -e cu130
# CONDA_OVERRIDE_CUDA=13.0 pixi add cuda-version=13.0 -p linux-64 -f cu130
cuda-version = "13.0.*"
# CONDA_OVERRIDE_CUDA=13.0 pixi add cuda-toolkit=13.0 -p linux-64 -f cu130
cuda-toolkit = "13.0.*"
# CONDA_OVERRIDE_CUDA=13.0 pixi add pytorch=2.10.0 torchvision -p linux-64 -f cu130
pytorch = "2.10.0.*"
torchvision = ">=0.25.0,<0.26"

[environments]
# default is implicit
default = { features = ["cu129"] }
# default = { features = ["cu130"] }
cu129 = { features = ["cu129"], no-default-feature = true }
cu130 = { features = ["cu130"], no-default-feature = true }

[activation.env]
# needs llvm-triton
PATH = "${PIXI_PROJECT_ROOT}/build/bin:${PIXI_PROJECT_ROOT}/llvm-triton/llvm-project/build/bin:${PATH}"
# only needed on macos
# CMAKE_PREFIX_PATH = "${CONDA_PREFIX}"

[target.osx-arm64.activation.env]
# lld is installed globaly, always prefer lld on osx
# `llnl-hatchet` needs lld
LDFLAGS = "-fuse-ld=lld"
